// <auto-generated />
using System;
using EntityIntro21._01._22.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityIntro21._01._22.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220121181812_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityIntro21._01._22.Data.Models.FootballTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("GoalsConceded")
                        .HasColumnType("smallint");

                    b.Property<short?>("GoalsScored")
                        .HasColumnType("smallint");

                    b.Property<short?>("Loss")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Win")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("FootballTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
